name: single-spa-angular

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v1
        id: yarn-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn

      - uses: actions/setup-node@v1
        with:
          node-version: 12.12

      - name: Install dependencies
        # Do not install dependencies again if checksum for the
        # `yarn.lock` is the same.
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn --pure-lockfile --non-interactive --no-progress

      - name: Run ESLint
        run: yarn lint

      - name: Build packages
        run: yarn build

      - name: Run Jest
        run: yarn test:ci

      - name: Install and build integration apps
        run: |
          yarn install:integration
          yarn build:integration

      - name: Run end-to-end tests via Cypress
        run: yarn test:ci:integration
