name: single-spa-angular

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v1
        id: yarn-cache
        with:
          # We also specify `~/.cache` because Cypress binary is installed
          # in that location.
          path: |
            node_modules
            */*/node_modules
            ~/.cache
          key: ${{ runner.os }}-yarn-v1-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-v1

      - uses: actions/setup-node@v1
        with:
          node-version: 12.12

      - name: Install dependencies
        # Do not install dependencies again if checksum for the
        # `yarn.lock` is the same.
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn --pure-lockfile --non-interactive --no-progress

      - name: Run ESLint
        run: yarn lint

      - name: Run Jest
        run: yarn test:ci

      - name: Build packages
        run: yarn build

      - name: Install packages for integration apps
        run: |
          yarn install:integration:shop
          yarn install:integration:chat
          yarn install:integration:noop-zone
          yarn install:integration:portal

      - name: Build integration apps
        # Parallel builds are currently not supported.
        # https://github.com/angular/angular/issues/32431
        run: |
          yarn build:integration:shop
          yarn build:integration:chat
          yarn build:integration:noop-zone
          yarn build:integration:portal

      - name: Run end-to-end tests via Cypress
        run: yarn test:ci:integration
